---
title: " Desempenho do Congresso e Executivo"
output: 
  html_document:
    css: styles.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  fig.cap = '',
  fig.align = 'center',
  fig.width = 10,
  fig.height = 8
)
```

```{r}
library(tidyverse)
library(here)
library(hrbrthemes)
library(ggchicklet)
```

```{r}
path_report <- "reports/desempenho-congresso-e-executivo/"

parlamentares <- read_csv(here(paste0(path_report, "data/parlamentares.csv")), 
                          col_types = cols(id = "c")) %>% 
  rename(id_parlamentar = id) %>% 
  filter(em_exercicio == 1)

partidos_investimento_uf <- read_csv(here(paste0(path_report, "data/investimento_partidario.csv"))) %>% 
  rename(total_partido_uf = valor, n_candidatos_uf = numero_candidatos)

investimento <- read_csv(here(paste0(path_report, "data/investimento_partidario_parlamentar.csv")),
                           col_types = cols(id_parlamentar = "c")) %>% 
  left_join(partidos_investimento_uf, by = c("partido_eleicao" = "sg_partido", "uf", "casa" = "esfera"))
```

```{r}

```

