ALTER TABLE votacoes
ADD COLUMN IF NOT EXISTS objeto_votacao VARCHAR DEFAULT NULL;

ALTER TABLE votacoes
ADD COLUMN IF NOT EXISTS horario TIMESTAMP DEFAULT NULL;

ALTER TABLE votacoes
ADD COLUMN IF NOT EXISTS codigo_sessao INTEGER DEFAULT NULL;