# CONSTANTS

# Urls
.URL_DEPUTADOS = "https://dadosabertos.camara.leg.br/api/v2/deputados/"

# Tipos de Votações
.PDL = "PROJETO DE DECRETO LEGISLATIVO"
.PEC_SEGUNDO_TURNO = "PROPOSTA DE EMENDA À CONSTITUIÇÃO - SEGUNDO TURNO"
.SUBEMENDA_SUBST_GLOBAL = "SUBEMENDA SUBSTITUTIVA GLOBAL"
.DESTAQUE = "DTQ. 4 - DEM - §4º DO ART. 47 DO SUBSTITUTIVO"
.EMENDA_SUBTS_GLOBAL = "EMENDA SUBSTITUTIVA GLOBAL DE PLENÁRIO Nº 1"
.SUBST_COM_ESPECIAL = "SUBSTITUTIVO DA COMISSÃO ESPECIAL"
.SUBST_RELATOR = "SUBSTITUTIVO OFERECIDO PELO RELATOR"
.PARECER_CM_ATEND_PRESSU_CONST = "PARECER DA C.M. P/ ATEND. DOS PRESSUPOSTOS CONSTITUCIONAIS..."
.SUBEMENDA_SUBST_CDEIC = "SUBEMENDA SUBSTITUTIVA DA CDEIC"
.VOT_ADMISS_GLOBO = "VOTAÇÃO DA ADMISSIBILIDADE, EM GLOBO, DOS DESTAQUES SIMPLES"
.SUBST_CFT = "SUBSTITUTIVO DA CFT"
.SUBEMENDA_SUBST = "SUBEMENDA SUBSTITUTIVA"
.SUBST_SF = "SUBSTITUTIVO DO SENADO FEDERAL"
.PLC = "PROJETO DE LEI DE CONVERSÃO"
.EMENDA_AGLUT_4 = "EMENDA AGLUTINATIVA Nº 4"

.QUERY = paste0(
".//Votacao[
@ObjVotacao ='",  .PDL, "' or 
@ObjVotacao = '", .PEC_SEGUNDO_TURNO, "' or 
@ObjVotacao = '", .SUBEMENDA_SUBST_GLOBAL, "' or 
@ObjVotacao = '", .DESTAQUE, "' or
@ObjVotacao = '", .EMENDA_SUBTS_GLOBAL, "' or 
@ObjVotacao = '", .SUBST_COM_ESPECIAL, "' or 
@ObjVotacao = '", .SUBST_RELATOR, "' or 
@ObjVotacao = '", .PARECER_CM_ATEND_PRESSU_CONST, "' or 
@ObjVotacao = '", .SUBEMENDA_SUBST_CDEIC, "' or 
@ObjVotacao = '", .VOT_ADMISS_GLOBO, "' or 
@ObjVotacao = '", .SUBST_CFT, "' or 
@ObjVotacao = '", .SUBEMENDA_SUBST, "' or 
@ObjVotacao = '", .SUBST_SF, "' or 
@ObjVotacao = '", .PLC, "' or 
@ObjVotacao = '", .EMENDA_AGLUT_4, "']")
