---
title: "Alinhamento dos parlamentares com posições de Meio Ambiente"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  fig.cap = '',
  fig.align = 'center',
  fig.width = 7
)
```

```{r}
library(tidyverse)
library(here)
theme_set(theme_minimal())

source(here::here("reports/alinhamento-meio-ambiente/code/calculo_alinhamento.R"))
```

```{r}
deputados <- readr::read_csv(here::here("bd/data/parlamentares.csv"), col_types = cols(id_parlamentar_voz = "c")) %>% 
  filter(casa == "camara") %>% 
  select(id_parlamentar_voz, nome = nome_eleitoral, uf, partido, em_exercicio)
```

```{r}
posicoes <- readr::read_csv(here::here("crawler/raw_data/tabela_votacoes.csv"))
votacoes <- readr::read_csv(here::here("bd/data/votacoes.csv"), col_types = "ncn")

posicoes_ma <- posicoes %>% 
  filter(tema == "Meio Ambiente")

id_posicoes_ma <- posicoes_ma %>% distinct(id_sessao) %>% arrange(id_sessao) %>% pull(id_sessao)

votacoes_ma <- votacoes %>%
  filter(id_votacao %in% id_posicoes_ma)

rm(posicoes, votacoes)
```

```{r}
votacao_ideal <- tibble::tibble(id_votacao = id_posicoes_ma,
                                id_parlamentar_voz = rep("ideal", length(id_posicoes_ma)),
                                voto = c(-1, -1, -1, -1, -1, -1, 1))
```

```{r}
alinhamento_deputados <- votacoes_ma %>% 
  count(id_parlamentar_voz) %>% 
  select(-n) %>% 
  mutate(dados = purrr::map(id_parlamentar_voz,
                           calcular_alinhamento_parlamentar,
                           votacoes_ma,
                           votacao_ideal)) %>% 
  unnest(dados) %>% 
  select(-id_parlamentar_voz)
  
```

```{r}
alin_deputados <- alinhamento_deputados %>% 
  left_join(deputados, by = c("id_parlamentar_b" = "id_parlamentar_voz")) %>% 
  mutate(nome = stringr::str_to_title(nome))
```

# Distribuição do alinhamento dos Deputados ao Meio Ambiente
```{r}
alin_deputados %>% 
  filter(em_exercicio == 1) %>% 
  ggplot(aes(x = alinhamento)) +
  geom_histogram(binwidth = 0.03, fill = "#8E6396", color = "#35193A") +
  labs(y = "Nº de parlamentares")
```

# Número de posições dadas x Alinhamento com meio ambiente
```{r}
set.seed(99) # evita mudança na visualização
alin_deputados %>% 
  filter(em_exercicio == 1) %>% 
  ggplot(aes(x = alinhamento, y = perguntas_iguais)) +
  geom_jitter(alpha = 0.5) +
  scale_y_continuous(limits = c(0, 7), breaks = seq(0, max(alin_deputados$perguntas_iguais), 1), oob = scales::squish) +
  labs(x = "Alinhamento",
       y = "Nº de posições dadas",
       title = "Alinhamento x Número de posições dadas")
```

# Deputados com maior alinhamento ao Meio Ambiente
```{r}
paleta = c("#A8DBA8", "#79BD9A")

deputados_top20 <- alin_deputados %>% 
  filter(em_exercicio == 1) %>% 
  arrange(desc(alinhamento), desc(respostas_iguais)) %>% 
  head(20) %>% 
  mutate(info_alinhamento = paste0(respostas_iguais, "/", perguntas_iguais)) %>% 
  mutate(deputado = paste0(nome, " (", partido, "/", uf, ")"))

deputados_top20 %>% 
  ggplot(aes(x = forcats::fct_rev(factor(deputado, 
                                         levels = unique(deputado))
                                  ), y = alinhamento * 100)) +
  geom_col(color = paleta[2], fill = paleta[1],  width = .5) +
  geom_text(
    aes(label = info_alinhamento), 
    hjust = -0.5, size = 3,
    position = position_dodge(width = 1),
    inherit.aes = TRUE
  ) +
  coord_flip() + 
  labs(x = "Deputados", y = "Alinhamento (%)", title = "20 deputados com maior alinhamento ao Meio Ambiente")
```

```{r}
paleta = c("#A8DBA8", "#79BD9A")

alin_deputados %>% 
  filter(em_exercicio == 1) %>% 
  arrange(desc(alinhamento), desc(respostas_iguais)) %>% 
  head(20) %>% 
  mutate(info_alinhamento = paste0(respostas_iguais, "/", perguntas_iguais)) %>% 
  mutate(deputado = paste0(nome, " (", partido, "/", uf, ")")) %>% 
  ggplot(aes(x = forcats::fct_rev(factor(deputado, 
                                         levels = unique(deputado))
                                  ), y = alinhamento * 100)) +
  geom_point(color = paleta[2], fill = paleta[1], size = 3, shape = 15) +
  geom_text(aes(label = info_alinhamento), hjust = -0.5, vjust = 0.4, size = 3) + 
  coord_flip() + 
  scale_y_continuous(limit = c(0, 105)) +
  labs(x = "Deputados", y = "Alinhamento (%)", title = "20 deputados com maior alinhamento ao Meio Ambiente")
```

```{r}

```



